name: Deploy Application

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.1'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci --engine-strict=false

      # Step 4: Set Environment Variables (for the entire job)
      - name: Set environment variables
        run: |
          echo "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> $GITHUB_ENV
          echo "FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}" >> $GITHUB_ENV
          echo "FIREBASE_DATABASE_URL=${{ secrets.FIREBASE_DATABASE_URL }}" >> $GITHUB_ENV
          echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> $GITHUB_ENV
          echo "FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}" >> $GITHUB_ENV
          echo "FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" >> $GITHUB_ENV
          echo "FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" >> $GITHUB_ENV
          echo "FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}" >> $GITHUB_ENV
          echo "MOVIE_API_URL=${{ secrets.MOVIE_API_URL }}" >> $GITHUB_ENV
          echo "SHOW_API_URL=${{ secrets.SHOW_API_URL }}" >> $GITHUB_ENV
          echo "FEED_API_URL=${{ secrets.FEED_API_URL }}" >> $GITHUB_ENV
          echo "USER_API_URL=${{ secrets.USER_API_URL }}" >> $GITHUB_ENV

      # Step 5: Replace Placeholders in src/assets/config.json
      - name: Replace Placeholders in config.json
        run: |
          sed -i "s|__API_KEY__|${{ secrets.FIREBASE_API_KEY }}|g" src/assets/config.json
          sed -i "s|__AUTH_DOMAIN__|${{ secrets.FIREBASE_AUTH_DOMAIN }}|g" src/assets/config.json
          sed -i "s|__DATABASE_URL__|${{ secrets.FIREBASE_DATABASE_URL }}|g" src/assets/config.json
          sed -i "s|__PROJECT_ID__|${{ secrets.FIREBASE_PROJECT_ID }}|g" src/assets/config.json
          sed -i "s|__STORAGE_BUCKET__|${{ secrets.FIREBASE_STORAGE_BUCKET }}|g" src/assets/config.json
          sed -i "s|__MSG_SENDER_ID__|${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}|g" src/assets/config.json
          sed -i "s|__APP_ID__|${{ secrets.FIREBASE_APP_ID }}|g" src/assets/config.json
          sed -i "s|__MEASUREMENT_ID__|${{ secrets.FIREBASE_MEASUREMENT_ID }}|g" src/assets/config.json
          sed -i "s|__MOVIE_URL__|${{ secrets.MOVIE_API_URL }}|g" src/assets/config.json
          sed -i "s|__SHOW_URL__|${{ secrets.SHOW_API_URL }}|g" src/assets/config.json
          sed -i "s|__FEED_URL__|${{ secrets.FEED_API_URL }}|g" src/assets/config.json
          sed -i "s|__USER_URL__|${{ secrets.USER_API_URL }}|g" src/assets/config.json

      # Step 6: Verify Placeholder Replacement
      - name: Verify config.json
        run: |
          echo "Validating config.json replacement"
          grep -E '__[A-Z_]+__' src/assets/config.json && exit 1 || echo "All placeholders replaced."

      # Step 7: Build the Angular application
      - name: Build Angular App
        run: npm run build -- --configuration production --output-path=docs --base-href /EntLib/

      # Step 8: Upload build artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: docs/

      # Step 9: Clean workspace
      - name: Clean workspace
        run: |
          rm -rf node_modules/
          npm cache clean --force

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Firebase Install 
        run: npm install firebase @angular/fire

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting --project entertaimentlib-ad956

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
