name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci --engine-strict=false

      - name: Verify File Exists
        run: |
          if [ ! -f src/assets/config.json ]; then 
            echo "src/assets/config.json NOT FOUND"
            exit 1
          else 
            echo "src/assets/config.json exists"
            cat src/assets/config.json
          fi

      - name: Set environment variables and replace placeholders
        run: |
          API_KEY="${{ secrets.FIREBASE_API_KEY }}"
          API_KEY_ESCAPED=$(printf '%s\n' "$API_KEY" | sed 's/[&/\]/\\&/g')
          sed -i 's|__API_KEY__|'"$API_KEY_ESCAPED"'|g' src/assets/config.json

      - name: Verify Placeholder Replacement
        run: |
          cat src/assets/config.json
          grep -E '__[A-Z_]+__' src/assets/config.json && exit 1 || echo "All placeholders replaced successfully."
